lib/urls.py
from django.urls import path
from . import views

app_name = "lib"

urlpatterns = [
    path('', views.index, name='index'),
    # path('book/all/', views.book_list, name='book-list'),
    path('book/all/', views.BookListView.as_view(), name='book-list'),
    # path('author/all/', views.author_list, name='author-list'),
    path('author/all/', views.AuthorListView.as_view(), name='author-list'),
    # path('genre/all/', views.genre_list, name='genre-list'),
    path('genre/all/', views.GenreListView.as_view(), name='genre-list'),
    # path('book/<int:pk>/', views.book_detail, name='book-detail'),
    path('book/<int:pk>/', views.BookDetailView.as_view(), name='book-detail'),
    # path('author/<int:pk>/', views.author_detail, name='author-detail'),
    path('author/<int:pk>/', views.AuthorDetailView.as_view(), name='author-detail'),
    path('comment/add/', views.add_comment, name='add-comment'),
    path('book/order/', views.edit_order, name='edit-order'),
]

project2/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('lib/', include('lib.urls')),
]

lib/models.py
from django.db import models
import datetime

from django.urls import reverse


class Author(models.Model):
    first_name = models.CharField(max_length=128)
    last_name = models.CharField(max_length=128)
    born = models.DateField(null=True, blank=True)
    portrait = models.URLField(null=True, blank=True)

    def __str__(self):
        return f'{self.first_name} {self.last_name}'

    def genres(self):
        genre_list = []
        for book in self.books.all():
            for genre in book.genres.all():
                if genre not in genre_list:
                    genre_list.append(genre)
        return sorted(genre_list, key=lambda g: g.name)


    # def comments(self):
    #     comments_list = []
    #     for book in self.books.all():
    #         for comment in book.comments.all():
    #             comments_list.append(comment)
    #     return sorted(comments_list, key=lambda c: c.published, reverse=True)


    def comments(self):
        return Comment.objects.filter(book__author__id__exact=self.id).order_by("-published")


    def url(self):
        return reverse('lib:author-detail', kwargs={'pk': self.id})

    class Meta:
        ordering = ['last_name', 'first_name']


class Genre(models.Model):
    name = models.CharField(max_length=128)

    def __str__(self):
        return self.name

    class Meta:
        ordering = ['name']

    def url(self):
        return reverse('lib:genre-list') + f'#section{self.id}'


class Book(models.Model):
    title = models.CharField(max_length=258)
    author = models.ForeignKey(Author, on_delete=models.SET_NULL, null=True, related_name='books')
    summary = models.TextField(null=True, blank=True)
    genres = models.ManyToManyField(Genre, related_name='books')
    cover = models.URLField(null=True, blank=True)

    def __str__(self):
        return self.title

    def url(self):
        return reverse('lib:book-detail', kwargs={'pk': self.id})

    class Meta:
        ordering = ['title']


class BookInstance(models.Model):
    book = models.ForeignKey(Book, on_delete=models.SET_NULL, null=True, related_name='instances')
    LOAN_STATUS = (
        ('a', 'available'),
        ('o', 'on loan'),
        ('m', 'maintenance'),
        ('r', 'reserved')
    )
    status = models.CharField(max_length=1, choices=LOAN_STATUS, default='m')
    due_back = models.DateField(null=True, blank=True)

    def __str__(self):
        return f'{self.id} - {self.book} - "{self.status}"'


class Comment(models.Model):
    book = models.ForeignKey(Book, on_delete=models.CASCADE, related_name='comments')
    author = models.CharField(max_length=128)
    text = models.TextField()
    published = models.DateTimeField(default=datetime.datetime.now)

lib/views.py
# from django.http import HttpResponse
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.views.generic import ListView, DetailView
from datetime import timedelta

from .models import *


def index(request):

    # data = Comment.objects.filter(book__author__id__exact=4)
    # print('-' * 20)
    # for item in data:
    #     print(item.text, item.book, item.book.author)
    # print('-' * 20)

    return render(request, template_name='lib/index.html')


# def book_list(request):
#     context = {
#         'books': Book.objects.order_by('title'),
#     }
#     return render(request, template_name='lib/book_list.html', context=context)


class BookListView(ListView):
    model = Book


# def author_list(request):
#     context = {
#         'authors': Author.objects.all(),
#     }
#     return render(request, template_name='lib/author_list.html', context=context)

class AuthorListView(ListView):
    model = Author
    template_name = 'lib/authors.html'
    context_object_name = 'authors'
    # queryset = Author.objects.filter(last_name__istartswith='d')

# def genre_list(request):
#     context = {
#         'genres': Genre.objects.all(),
#     }
#     return render(request, template_name='lib/genre_list.html', context=context)

class GenreListView(ListView):
    model = Genre

# def book_detail(request, pk):
#     context = {
#         'book': Book.objects.get(id__exact=pk),
#     }
#     return render(request, template_name='lib/book_detail.html', context=context)

class BookDetailView(DetailView):
    model = Book

# def author_detail(request, pk):
#     context = {
#         'author': Author.objects.get(pk=pk),
#     }
#     return render(request, template_name='lib/author_detail.html', context=context)


class AuthorDetailView(DetailView):
    model = Author


def add_comment(request):
    author = request.POST.get('author')
    text = request.POST.get('text')
    book_id = request.POST.get('book_id')
    if author and text:
        new_comment = Comment(author=author, text=text, book_id=book_id)
        new_comment.save()
    return HttpResponseRedirect(reverse('lib:book-detail', kwargs={'pk': book_id}))


def edit_order(request):
    bi_id = request.POST.get('bi_id')
    bi = BookInstance.objects.get(id=bi_id)
    due_back = datetime.datetime.now() + timedelta(days=7)
    bi.status = 'o'
    bi.due_back = due_back
    book_id = bi.book_id
    bi.save()
    return HttpResponseRedirect(reverse('lib:book-detail', kwargs={'pk': book_id}))

lib/templates/lib/author_detail.html
{% extends 'lib/base.html' %}

{% block title %}
{{ author }}
{% endblock %}

{% block main %}
<h1 class="text-primary text-center">{{ object }}</h1>
<hr>

<div class="row mt-5">   
     <div class="col-2">
         <img src="{{ author.portrait }}" class="img-fluid img-thumbnail">
     </div>
     <div class="col-3">
         {% for genre in author.genres %}
            <a href="#">{{genre}}</a><br>
         {% endfor %} 
     </div>
     <div class="col-3 text-center">
         <h3>Books:</h3>
         {% for book in author.books.all %}
            <a href="{{ book.url }}" class="text-decoration-none">
                <h5>{{ book }}</h5>
            </a>
         {% endfor %}
     </div>
     <div class="col-4">
        <h3 class="text-center">Comments:</h3>
        {% for comment in author.comments %}
            <p>{{ comment.author }} about 
                <a href="{{comment.book.url}}">{{ comment.book }}</a>
                : {{comment.text}} <br>
                <i>({{ comment.published }})</i> 
            </p>
        {% endfor %} 
     </div>
</div>





{% endblock %}

lib/templates/lib/authors.html
{% extends 'lib/base.html' %}

{% block title %}
All Authors
{% endblock %}

{% block main %}
<h1 class="text-primary text-center">All Authors</h1>

<div class="row mt-5">
    {% for author in authors %}
    <div class="col-4">
        <div class="row">
            <div class="col-4 py-2">
                <img src="{{ author.portrait }}" class="w-100">
            </div>
            <div class="col-8">
                <a href="{{ author.url }}" class="text-decoration-none ">
                    <h5 class="text-success">{{ author }}</h5>
                </a>
      
                <p style="font-size: 70%;">
                    {% for genre in author.genres %}
                    <a href="#">{{genre}}</a>
                    {% endfor %} 
                </p>
            </div>
        </div>
    </div>
    {% endfor %}  
</div>



{% endblock %}

lib/templates/lib/base.html
<!DOCTYPE html>
{%load static%}
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock %}</title>
    <link rel="shortcut icon" href="{% static 'lib/img/books.png' %}" type="image/x-icon">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
</head>
<body>
    <div class="container p-5">
        <div class="row">
            <div class="col-2">
                <a href="{% url 'lib:index' %}">
                    <img src="{% static 'lib/img/logo.png' %}" alt="" class="img-fluid">
                </a>
            </div>
        </div>

        {% block main %}{% endblock %}
        {% include 'lib/footer.html' %}

    </div>
</body>
</html>

lib/templates/lib/book_detail.html
{% extends 'lib/base.html' %}

{% block title %}
{{ book }}
{% endblock %}

{% block main %}
<h1 class="text-primary text-center">{{ object }}</h1>
<hr>

<div class="row mt-5">   
     <div class="col-2">
         <img src="{{ book.cover }}" class="img-fluid img-thumbnail">
     </div>
     <div class="col-3">
         <a href="{{ book.author.url }}" class="text-decoration-none">
             <h2 class="text-success">{{book.author}}</h2>
         </a>
         <br>
         {% for genre in book.genres.all %}
            <a href="{{ genre.url }}">{{genre}}</a><br>
         {% endfor %} 
     </div>
     {% if book.summary %}
        <div class="col-4">
            <h3>Summary:</h3>
            <p>{{book.summary}}</p>
        </div>
     {% endif %}
     {% if book.instances.all %}
     <div class="col-3">
         <h3>Instances ({{book.instances.all | length}}):</h3>
         <ul>
         {% for bi in book.instances.all %}
            <li>
                {{ bi.id }} - {{ bi.get_status_display }}
                {% if bi.status == 'o' %}
                    (till {{ bi.due_back | date:'d F' }})
                {% endif %}
                {% if bi.status == 'a' %}
                    <form action="{% url 'lib:edit-order' %}" method="POST">
                        {% csrf_token %}
                        <input type="hidden" name="bi_id" value="{{bi.id}}">
                        <button type="submit" class="btn btn-outline-primary btn-sm">Order</button>
                    </form>
                    
                {% endif %}
            </li>
         {% endfor%}
         </ul>
     </div>
    {% endif %}
</div>
<hr>

<form method="POST" action="{% url 'lib:add-comment' %}">
    {% csrf_token %}
    <div class="row">
        <div class="col">
            <input type="text" class="form-control" placeholder="author" name="author">
        </div>
        <div class="col">
            <input type="text" class="form-control" placeholder="comment" name="text">
            <input type="hidden" name="book_id" value="{{ book.id }}">
        </div>
        <div class="col">
            <input type="submit" value="Add" class="btn btn-primary mb-2">
        </div>
    </div>
</form>


{% endblock %}

lib/templates/lib/book_list.html
{% extends 'lib/base.html' %}

{% block title %}
All Books
{% endblock %}

{% block main %}
<h1 class="text-primary text-center">All Books</h1>

<div class="row">
    {% for book in object_list %}
    <div class="col-4">
        <div class="row">
            <div class="col-4 py-2">
                <img src="{{ book.cover }}" class="w-100">
            </div>
            <div class="col-8">
                <a href="{{ book.url }}" class="text-decoration-none">
                    <h5>{{ book }}</h5>
                </a>
                <a href="{{ book.author.url }}" class="text-decoration-none text-success">
                    <h6>{{ book.author }}</h6>
                </a>
                <p style="font-size: 70%;">
                    {% for genre in book.genres.all %}
                    <a href="#">{{genre}}</a>
                    {% endfor %} 
                </p>
            </div>
        </div>
    </div>
    {% endfor %}  
</div>



{% endblock %}

lib/templates/lib/footer.html
{%load static%}
<div class="row mt-5">
    <div class="col-12">
        <img src="{% static 'lib/img/banner.jpg' %}" alt="" class="w-100">
    </div>
</div>

lib/templates/lib/genre_list.html
{% extends 'lib/base.html' %}

{% block title %}
All Genres
{% endblock %}

{% block main %}
<h1 class="text-primary text-center">All Genres</h1>

{% for genre in object_list %}
<a name="section{{genre.id}}"></a>
<h2 class="mt-3">{{ genre }} ({{genre.books.all| length}})</h2>

<div class="row">
    {% for book in genre.books.all %}
    <div class="col-4">
        <div class="row">
            <div class="col-4 py-2">
                <img src="{{ book.cover }}" class="w-100">
            </div>
            <div class="col-8">
                <a href="{{ book.url }}" class="text-decoration-none">
                    <h5>{{ book }}</h5>
                </a>
                <a href="{{ book.author.url }}" class="text-decoration-none text-success">
                    <h6>{{ book.author }}</h6>
                </a>
                <p style="font-size: 70%;">
                    {% for genre1 in book.genres.all %}
                    <a href="{{genre1.url}}">{{genre1}}</a>
                    {% endfor %} 
                </p>
            </div>
        </div>
    </div>
    {% endfor %}  
</div>
<a href="{% url 'lib:genre-list' %}#section{{genre.id}}">up</a>
<hr>

{% endfor %}
{% endblock %}

lib/templates/lib/index.html
{% extends 'lib/base.html' %}

{% block title %}
Polygon Lib.
{% endblock %}

{% block main %}
<h1 class="text-primary text-center">Polygon Library</h1>
<hr>

<div class="row">
    <div class="col-4">
        <a href="{% url 'lib:book-list' %}">
            <h2 class="text-primary text-center">All Books</h2>
        </a>
    </div>
    <div class="col-4">
        <a href="{% url 'lib:author-list' %}">
            <h2 class="text-primary text-center">All Authors</h2>
        </a>
    </div>
    <div class="col-4">
        <a href="{% url 'lib:genre-list' %}">
            <h2 class="text-primary text-center">Books by Genre</h2>
        </a>
    </div>
</div>



{% endblock %}